---
# - name: Get available storage devices for HANA VG
#   set_fact: 
#     data_disk: "{{ data_disk|default([]) + [device.key] }}"
#   when:
#      - not device.value.partitions
#      - not device.value.holders
#      - device.key is search('vd')
#      - device.value.size == hana_disk_size
#   loop: "{{ ansible_devices | dict2items }}"
#   loop_control:
#     loop_var: device

- name: Check if the required storage device for HANA VG is found
  debug:
    var: "{{ hana_disk_size }}"
...
