---
- name: Create /usr/sap/kit directory
  file:
    path: "{{ sap_kit }}"
    state: directory
    mode: 0777

- name: Create /usr/sap/kit/swpm directory
  file:
    path: "{{ sap_kit }}/swpm"
    state: directory
    mode: 0777

- name: Create /usr/sap/kit/export directory
  file:
    path: "{{ sap_kit }}/export"
    state: directory
    mode: 0777

- name: Create /usr/sap/kit/db2 directory
  file:
    path: "{{ sap_kit }}/db2"
    state: directory
    mode: 0777

- name: Create /usr/sap/kit/db2client directory
  file:
    path: "{{ sap_kit }}/db2client"
    state: directory
    mode: 0777

- name: Copy "{{ kit_sapcar_file }}" kit to target
  copy:
    src: "{{ kit_sapcar_file }}"
    dest: "{{ sap_kit }}/sapcar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_swpm_file }}" kit to target
  copy:
    src: "{{ kit_swpm_file }}"
    dest: "{{ sap_kit }}/swpm.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_saphotagent_file }}" kit to target
  copy:
    src: "{{ kit_saphotagent_file }}"
    dest: "{{ sap_kit }}/saphotagent.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexe_file }}" kit to target
  copy:
    src: "{{ kit_sapexe_file }}"
    dest: "{{ sap_kit }}/sapexe.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexedb_file }}" kit to target
  copy:
    src: "{{ kit_sapexedb_file }}"
    dest: "{{ sap_kit }}/sapexedb.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_export_dir }}" kit to target
  copy:
    src: "{{ kit_export_dir }}/"
    dest: "{{ sap_kit }}/export/"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_db2_dir }}" kit to target
  copy:
    src: "{{ kit_db2_dir }}/"
    dest: "{{ sap_kit }}/db2/"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_db2client_dir }}" kit to target
  copy:
    src: "{{ kit_db2client_dir }}/"
    dest: "{{ sap_kit }}/db2client/"
    owner: root
    group: root
    mode: 0777

- name: Extract SWPM archive
  command: "{{ sap_kit }}/sapcar -xf {{ sap_kit }}/swpm.sar -R {{ sap_kit }}/swpm"
...   