---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Import playbook variables
      include_vars: "saphanadbstandby-vars.yml"
  roles:
    - saphanareq
    - saphanainst
    - saphsrstandby
...
