---
- name: Create /usr/sap/trans/kit directory
  file:
    path: "{{ sap_kit }}"
    state: directory
    mode: 0777

- name: Create /usr/sap/trans/kit/swpm directory
  file:
    path: "{{ sap_kit }}/swpm"
    state: directory
    mode: 0777

- name: Create /usr/sap/trans/kit/export directory
  file:
    path: "{{ sap_kit }}/export"
    state: directory
    mode: 0777

- name: Create /usr/sap/trans/kit/db2 directory
  file:
    path: "{{ sap_kit }}/db2"
    state: directory
    mode: 0777

- name: Create /usr/sap/trans/kit/db2client directory
  file:
    path: "{{ sap_kit }}/db2client"
    state: directory
    mode: 0777

- name: Copy "{{ kit_sapcar_file }}" kit to target
  synchronize:
    src: "{{ kit_sapcar_file }}"
    dest: "{{ sap_kit }}/sapcar"
    checksum: yes

- name: Copy "{{ kit_swpm_file }}" kit to target
  synchronize:
    src: "{{ kit_swpm_file }}"
    dest: "{{ sap_kit }}/swpm.sar"
    checksum: yes

- name: Copy "{{ kit_saphotagent_file }}" kit to target
  synchronize:
    src: "{{ kit_saphotagent_file }}"
    dest: "{{ sap_kit }}/saphotagent.sar"
    checksum: yes

- name: Copy "{{ kit_sapexe_file }}" kit to target
  synchronize:
    src: "{{ kit_sapexe_file }}"
    dest: "{{ sap_kit }}/sapexe.sar"
    checksum: yes

- name: Copy "{{ kit_sapexedb_file }}" kit to target
  synchronize:
    src: "{{ kit_sapexedb_file }}"
    dest: "{{ sap_kit }}/sapexedb.sar"
    checksum: yes

- name: Copy "{{ kit_igsexe_file }}" kit to target
  synchronize:
    src: "{{ kit_igsexe_file }}"
    dest: "{{ sap_kit }}/igsexe.sar"
    checksum: yes

- name: Copy "{{ kit_igshelper_file }}" kit to target
  synchronize:
    src: "{{ kit_igshelper_file }}"
    dest: "{{ sap_kit }}/igshelper.sar"
    checksum: yes

- name: Copy "{{ kit_export_dir }}" kit to target
  synchronize:
    src: "{{ kit_export_dir }}/"
    dest: "{{ sap_kit }}/export/"
    checksum: yes

- name: Copy "{{ kit_db2_dir }}" kit to target
  synchronize:
    src: "{{ kit_db2_dir }}/"
    dest: "{{ sap_kit }}/db2/"
    checksum: yes

- name: Copy "{{ kit_db2client_dir }}" kit to target
  synchronize:
    src: "{{ kit_db2client_dir }}/"
    dest: "{{ sap_kit }}/db2client/"
    checksum: yes

- name: Recursively change ownership of a directory
  file:
    path: "{{ sap_kit }}"
    state: directory
    mode: 0777
    recurse: yes
    owner: root
    group: root

- name: Extract SWPM archive
  command: "{{ sap_kit }}/sapcar -xf {{ sap_kit }}/swpm.sar -R {{ sap_kit }}/swpm"
...
