---
- name: Create /usr/sap/kit directory
  file:
    path: "{{ javaci_kit }}"
    state: directory
    mode: 0777

- name: Create /usr/sap/trans/kit/swpm directory
  file:
    path: "{{ javaci_kit }}/swpm"
    state: directory
    mode: 0777

- name: Create /usr/sap/trans/kit/hdbclient directory
  file:
    path: "{{ javaci_kit }}/hdbclient"
    state: directory
    mode: 0777

- name: Create /usr/sap/trans/kit/export directory
  file:
    path: "{{ javaci_kit }}/export"
    state: directory
    mode: 0777

- name: Copy "{{ kit_sapcar_file }}" kit to target
  copy:
    src: "{{ kit_sapcar_file }}"
    dest: "{{ javaci_kit }}/sapcar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_swpm_file }}" kit to target
  copy:
    src: "{{ kit_swpm_file }}"
    dest: "{{ javaci_kit }}/swpm.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexe_file }}" kit to target
  copy:
    src: "{{ kit_sapexe_file }}"
    dest: "{{ javaci_kit }}/sapexe.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexedb_file }}" kit to target
  copy:
    src: "{{ kit_sapexedb_file }}"
    dest: "{{ javaci_kit }}/sapexedb.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_igsexe_file }}" kit to target
  copy:
    src: "{{ kit_igsexe_file }}"
    dest: "{{ javaci_kit }}/igsexe.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_igshelper_file }}" kit to target
  copy:
    src: "{{ kit_igshelper_file }}"
    dest: "{{ javaci_kit }}/igshelper.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_saphotagent_file }}" kit to target
  copy:
    src: "{{ kit_saphotagent_file }}"
    dest: "{{ javaci_kit }}/saphotagent.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_hdbclient_file }}" kit to target
  copy:
    src: "{{ kit_hdbclient_file }}"
    dest: "{{ javaci_kit }}/hdbclient.sar"
    owner: root
    group: root
    mode: 0777

- name: Extract HDBClient archive
  command: "{{ javaci_kit }}/sapcar -xf {{ javaci_kit }}/hdbclient.sar -R {{ javaci_kit }}/hdbclient"

- name: Copy "{{ kit_sapjvm_file }}" kit to target
  copy:
    src: "{{ kit_sapjvm_file }}"
    dest: "{{ javaci_kit }}/sapjvm.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_java_export }}" kit to target
  copy:
    src: "{{ kit_java_export }}/"
    dest: "{{ javaci_kit }}/export"
    owner: root
    group: root
    mode: 0777

- name: Extract SWPM archive
  command: "{{ javaci_kit }}/sapcar -xf {{ javaci_kit }}/swpm.sar -R {{ javaci_kit }}/swpm"
...
