---
- name: Configure db hostname in /etc/hosts file
  include_tasks: "db_host.yml"

- name: Generate parameter file for sapinst
  template:
      src: sapinst.cfg
      dest: "{{ sap_kit }}/pas_inifile.params"

- name: Start SAP installation
  shell: "{{ sap_kit }}/swpm/sapinst SAPINST_INPUT_PARAMETERS_URL={{ sap_kit }}/pas_inifile.params SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false"

- name: Cleanup
  file:
    path: "{{ sap_kit }}"
    state: absent
...