# Export Terraform variable values to an Ansible var_file
resource "local_file" "db_ansible_saphanadb-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#HANA system configuration
hana_sid: "${var.hana_sid}"
hana_sysno: "${var.hana_sysno}"
hana_system_usage: "${var.hana_system_usage}"
hana_components: "${var.hana_components}"
sap_master_password: "${var.sap_master_password}"
dbstandby_host: "${module.dbstandby-vsi.PRIVATE-IP}"
dbstandby_hostname: "${var.DBSTANDBY-HOSTNAME}"

#SAP HANA Installation kit path
kit_saphana_file: "${var.kit_saphana_file}"
...
    DOC
  filename = "../ansible/saphanadb-vars.yml"
}
