# Export Terraform variable values to an Ansible var_file
resource "local_file" "app_ansible_javaci-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.sap_sid}"
sap_scs_instance_number: "${var.sap_scs_instance_number}"
sap_ci_instance_number: "${var.sap_ci_instance_number}"
sap_master_password: "${var.sap_master_password}"

#HANA config
hdb_host: "${module.db-vsi.PRIVATE-IP}"
hdb_sid: "${var.hana_sid}"
hdb_instance_number: "${var.hana_sysno}"

#SAP JAVA CI Installation kit path
kit_sapcar_file: "${var.kit_sapcar_file}"
kit_swpm_file: "${var.kit_swpm_file}"
kit_sapexe_file: "${var.kit_sapexe_file}"
kit_sapexedb_file: "${var.kit_sapexedb_file}"
kit_igsexe_file: "${var.kit_igsexe_file}"
kit_igshelper_file: "${var.kit_igshelper_file}"
kit_saphotagent_file: "${var.kit_saphotagent_file}"
kit_hdbclient_file: "${var.kit_hdbclient_file}"
kit_sapjvm_file: "${var.kit_sapjvm_file}"
kit_java_export: "${var.kit_java_export}"
...
    DOC
  filename = "ansible/javaci-vars.yml"
}
