---
- name: Import OS distribution variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Import requierd package groups
  dnf:
    state: present
    name: "{{ sapnw_required_package_groups }}" 

- name: Import required packages
  package:
    state: present
    name: "{{ sapnw_required_packages }}"

- name: Make specific OS configurations as recommended by SAP
  include_tasks: "configurations/{{ item }}.yml"
  loop: "{{ sapnw_required_configurations }}"
...
