---
s4app_required_packages:
s4app_required_package_groups:
  - "@large-systems"
  - "@network-file-system-client"
  - "@performance"
  - "@compat-libraries"
s4app_required_configurations:
  - "reqpkggroups"
  - "reqpkg"
  - "update_os"
...
