---
- name: Create /usr/sap/kit directory
  file:
    path: "{{ hana_kit }}"
    state: directory
    mode: 0777

- name: Copy "{{ kit_saphana_file }}" kit to target
  copy:
    src: "{{ kit_saphana_file }}"
    dest: "{{ hana_kit }}"
    owner: root
    group: root
    mode: 0777
...
