---
# - name: Import install kit
#   include_tasks: "install_kit.yml"

- name: Generate parameter file for hdblcm
  template:
      src: hanaconfig.cfg
      dest: "{{ hana_kit }}/hanaconfig.cfg"
...
