---
- name: Set recommended kernel parameters for SAP NW on RedHat 8
  sysctl:
    sysctl_file: /etc/sysctl.d/sap.conf
    name: "{{ kernel_param.name }}"
    value: "{{ kernel_param.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { name: vm.max_map_count, value: 2147483647 }
    - { name: kernel.pid_max, value: 4194304 }
    - { name: kernel.sem, value: "32000 1024000000 500 32000" }
  loop_control:
    loop_var: kernel_param  
...